name: Run MATLAB Tests
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:
jobs:
  matlab-test:
    name: Run MATLAB Tests
    strategy:
      fail-fast: false
      matrix:
        version: ["R2020a", "R2020b", "R2021a", "R2021b", "R2022a", "R2022b"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        exclude:
          - os: windows-latest
            version: "R2020a" # MATLAB not available
          - os: windows-latest
            version: "R2020b" # MATLAB not available
          - os: windows-latest
            version: "R2021a" # Compiler not available
          - os: windows-latest
            version: "R2021b" # Compiler not available
    runs-on: ${{matrix.os}}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: ${{matrix.version}}
      - name: Run tests with existing MEX files
        uses: matlab-actions/run-command@v1
        with:
          command: addpath(pwd); results = runtests('tests'), assertSuccess(results);
      - name: Compile MEX file
        run: mex jsonread.c jsmn.c -DJSMN_PARENT_LINKS
      - name: Run tests with newly compiled MEX files
        uses: matlab-actions/run-command@v1
        with:
          command: addpath(pwd); results = runtests('tests'), assertSuccess(results);
      - name: Get MEX extension
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            echo "MEXEXT=$(mexext)" >> $GITHUB_ENV
          elif [ "$RUNNER_OS" == "macOS" ]; then
            echo "MEXEXT=$(mexext)" >> $GITHUB_ENV
          elif [ "$RUNNER_OS" == "Windows" ]; then
            echo "MEXEXT=$(mexext)" >> $env:GITHUB_ENV
          else
            echo "$RUNNER_OS not supported"
            exit 1
          fi
        shell: bash
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jsonio-mex-${{matrix.os}}-${{matrix.version}}
          path: ./**/*.${{env.MEXEXT}}
          retention-days: 5
